//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::AccessType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cache_access")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub cache_id: Uuid,
  pub user_id: Option<Uuid>,
  pub group_id: Option<Uuid>,
  pub access_type: AccessType,
  #[sea_orm(
    belongs_to,
    from = "cache_id",
    to = "id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  pub cache: BelongsTo<super::cache::Entity>,
  #[sea_orm(
    belongs_to,
    from = "group_id",
    to = "id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  pub group: BelongsTo<Option<super::group::Entity>>,
  #[sea_orm(
    belongs_to,
    from = "user_id",
    to = "id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
