//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::EvictionPolicy;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cache")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub priority: i32,
  pub public: bool,
  pub quota: i64,
  pub public_signing_key: String,
  pub allow_force_push: bool,
  pub eviction_policy: EvictionPolicy,
  #[sea_orm(has_many)]
  pub cache_accesses: HasMany<super::cache_access::Entity>,
  #[sea_orm(has_many)]
  pub downstream_caches: HasMany<super::downstream_cache::Entity>,
  #[sea_orm(has_many)]
  pub nar_infos: HasMany<super::nar_info::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
