//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "downstream_cache")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub cache_id: Uuid,
  pub url: String,
  #[sea_orm(
    belongs_to,
    from = "cache_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub cache: BelongsTo<super::cache::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
