//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "downstream_cache")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub cache_id: Uuid,
  pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cache::Entity",
    from = "Column::CacheId",
    to = "super::cache::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Cache,
}

impl Related<super::cache::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Cache.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
