//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "nar")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub hash: String,
  pub size: i64,
  pub nar_hash: String,
  pub nar_size: i64,
  pub created_at: DateTime,
  #[sea_orm(has_many)]
  pub nar_infos: HasMany<super::nar_info::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
