//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "nar_info")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub cache_id: Uuid,
  pub nar_id: Uuid,
  pub store_path: String,
  pub store_path_hash: String,
  pub compression: String,
  pub deriver: Option<String>,
  pub signature: String,
  pub last_accessed_at: Option<DateTime>,
  pub created_at: DateTime,
  pub accessed: i64,
  #[sea_orm(
    belongs_to,
    from = "cache_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub cache: BelongsTo<super::cache::Entity>,
  #[sea_orm(
    belongs_to,
    from = "nar_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub nar: BelongsTo<super::nar::Entity>,
  #[sea_orm(has_many)]
  pub nar_info_references: HasMany<super::nar_info_reference::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
