//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "nar_info_reference")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub nar_info_id: Uuid,
  pub store_path: String,
  #[sea_orm(
    belongs_to,
    from = "nar_info_id",
    to = "id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  pub nar_info: BelongsTo<super::nar_info::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
