//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nar_info_reference")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub nar_info_id: Uuid,
  pub store_path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::nar_info::Entity",
    from = "Column::NarInfoId",
    to = "super::nar_info::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  NarInfo,
}

impl Related<super::nar_info::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NarInfo.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
