//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
  Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, JsonSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "access_type")]
pub enum AccessType {
  #[sea_orm(string_value = "edit")]
  Edit,
  #[sea_orm(string_value = "view")]
  View,
}
#[derive(
  Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, JsonSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "eviction_policy")]
pub enum EvictionPolicy {
  #[sea_orm(string_value = "oldest_first")]
  OldestFirst,
  #[sea_orm(string_value = "least_recently_used")]
  LeastRecentlyUsed,
  #[sea_orm(string_value = "least_frequently_used")]
  LeastFrequentlyUsed,
}
