// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape
} from './client';
import { client } from './client.gen';
import type {
  AuthConfigData,
  AuthConfigErrors,
  AuthConfigResponses,
  AuthenticateData,
  AuthenticateErrors,
  AvatarByIdData,
  AvatarByIdErrors,
  AvatarByIdResponses,
  CacheDetailsData,
  CacheDetailsErrors,
  CacheDetailsResponses,
  ChangeUserEmailData,
  ChangeUserEmailErrors,
  ChangeUserEmailResponses,
  ClearCacheData,
  ClearCacheErrors,
  ClearCacheResponses,
  CompleteSetupData,
  CompleteSetupErrors,
  ConfirmEmailChangeData,
  ConfirmEmailChangeErrors,
  ConfirmEmailChangeResponses,
  ConvertOidcUserData,
  ConvertOidcUserErrors,
  ConvertOidcUserResponses,
  CreateCacheData,
  CreateCacheErrors,
  CreateCacheResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateTokenData,
  CreateTokenErrors,
  CreateTokenResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteCacheData,
  DeleteCacheErrors,
  DeleteCacheResponses,
  DeleteExpiredTokensData,
  DeleteExpiredTokensErrors,
  DeleteExpiredTokensResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeletePathData,
  DeletePathErrors,
  DeletePathResponses,
  DeleteTokenData,
  DeleteTokenErrors,
  DeleteTokenResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  EditCacheData,
  EditCacheErrors,
  EditCacheResponses,
  EditGroupData,
  EditGroupErrors,
  EditGroupResponses,
  EditTokenData,
  EditTokenErrors,
  EditTokenResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  GetGeneralSettingsData,
  GetGeneralSettingsErrors,
  GetGeneralSettingsResponses,
  GetMailSettingsData,
  GetMailSettingsErrors,
  GetMailSettingsResponses,
  GetOidcSettingsData,
  GetOidcSettingsErrors,
  GetOidcSettingsResponses,
  GetTokenData,
  GetTokenErrors,
  GetTokenResponses,
  GetUserSettingsData,
  GetUserSettingsErrors,
  GetUserSettingsResponses,
  GroupInfoData,
  GroupInfoErrors,
  GroupInfoResponses,
  InfoData,
  InfoErrors,
  InfoResponses,
  InitOidcData,
  InitOidcErrors,
  InitOidcResponses,
  IsSetupData,
  IsSetupErrors,
  IsSetupResponses,
  KeyData,
  KeyResponses,
  ListCachesData,
  ListCachesErrors,
  ListCachesResponses,
  ListCachesSimpleData,
  ListCachesSimpleErrors,
  ListCachesSimpleGroupData,
  ListCachesSimpleGroupErrors,
  ListCachesSimpleGroupResponses,
  ListCachesSimpleResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsResponses,
  ListGroupsSimpleData,
  ListGroupsSimpleErrors,
  ListGroupsSimpleResponses,
  ListTokensData,
  ListTokensErrors,
  ListTokensResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  ListUsersSimpleData,
  ListUsersSimpleErrors,
  ListUsersSimpleResponses,
  LogoutData,
  LogoutErrors,
  MailActiveData,
  MailActiveErrors,
  MailActiveResponses,
  NewCodeData,
  NewCodeResponses,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarErrors,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  SaveMailSettingsData,
  SaveMailSettingsErrors,
  SaveMailSettingsResponses,
  SaveUserSettingsData,
  SaveUserSettingsErrors,
  SaveUserSettingsResponses,
  SearchStorePathsData,
  SearchStorePathsErrors,
  SearchStorePathsResponses,
  SendResetLinkData,
  SendResetLinkErrors,
  SendResetLinkResponses,
  StartEmailChangeData,
  StartEmailChangeErrors,
  StartEmailChangeResponses,
  TestData,
  TestErrors,
  TestMailData,
  TestMailErrors,
  TestMailResponses,
  TestResponses,
  TestTokenData,
  TokenInfoData,
  TokenInfoErrors,
  TokenInfoResponses,
  TokenRegenerateData,
  TokenRegenerateErrors,
  TokenRegenerateResponses,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarErrors,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordErrors,
  UpdatePasswordResponses,
  UploadFinishData,
  UploadFinishErrors,
  UploadFinishResponses,
  UploadInfoData,
  UploadInfoErrors,
  UploadInfoResponses,
  UploadNarData,
  UploadNarErrors,
  UploadNarResponses,
  UploadPathData,
  UploadPathErrors,
  UploadPathResponses,
  UserInfoDetailData,
  UserInfoDetailErrors,
  UserInfoDetailResponses
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const isSetup = <ThrowOnError extends boolean = false>(
  options?: Options<IsSetupData, ThrowOnError>
): RequestResult<IsSetupResponses, IsSetupErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    IsSetupResponses,
    IsSetupErrors,
    ThrowOnError
  >({ url: '/api/setup', ...options });

export const completeSetup = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSetupData, ThrowOnError>
): RequestResult<unknown, CompleteSetupErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, CompleteSetupErrors, ThrowOnError>({
    url: '/api/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getOidcSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetOidcSettingsData, ThrowOnError>
): RequestResult<
  GetOidcSettingsResponses,
  GetOidcSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetOidcSettingsResponses,
    GetOidcSettingsErrors,
    ThrowOnError
  >({ url: '/api/setup/oidc', ...options });

export const initOidc = <ThrowOnError extends boolean = false>(
  options: Options<InitOidcData, ThrowOnError>
): RequestResult<InitOidcResponses, InitOidcErrors, ThrowOnError> =>
  (options.client ?? client).post<
    InitOidcResponses,
    InitOidcErrors,
    ThrowOnError
  >({
    url: '/api/setup/oidc',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
): RequestResult<unknown, unknown, ThrowOnError> =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/api/auth/test_token',
    ...options
  });

export const key = <ThrowOnError extends boolean = false>(
  options?: Options<KeyData, ThrowOnError>
): RequestResult<KeyResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<KeyResponses, unknown, ThrowOnError>({
    url: '/api/auth/password',
    ...options
  });

export const authenticate = <ThrowOnError extends boolean = false>(
  options: Options<AuthenticateData, ThrowOnError>
): RequestResult<unknown, AuthenticateErrors, ThrowOnError> =>
  (options.client ?? client).post<unknown, AuthenticateErrors, ThrowOnError>({
    url: '/api/auth/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
): RequestResult<unknown, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/auth/logout',
    ...options
  });

export const authConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AuthConfigData, ThrowOnError>
): RequestResult<AuthConfigResponses, AuthConfigErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthConfigResponses,
    AuthConfigErrors,
    ThrowOnError
  >({ url: '/api/auth/config', ...options });

export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: '/api/user/management', ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editUser = <ThrowOnError extends boolean = false>(
  options: Options<EditUserData, ThrowOnError>
): RequestResult<EditUserResponses, EditUserErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const mailActive = <ThrowOnError extends boolean = false>(
  options?: Options<MailActiveData, ThrowOnError>
): RequestResult<MailActiveResponses, MailActiveErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    MailActiveResponses,
    MailActiveErrors,
    ThrowOnError
  >({ url: '/api/user/management/mail', ...options });

export const listGroupsSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsSimpleData, ThrowOnError>
): RequestResult<
  ListGroupsSimpleResponses,
  ListGroupsSimpleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGroupsSimpleResponses,
    ListGroupsSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/groups', ...options });

export const resetUserAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserAvatarData, ThrowOnError>
): RequestResult<
  ResetUserAvatarResponses,
  ResetUserAvatarErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ResetUserAvatarResponses,
    ResetUserAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/management/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>
): RequestResult<
  ResetUserPasswordResponses,
  ResetUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/management/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const changeUserEmail = <ThrowOnError extends boolean = false>(
  options: Options<ChangeUserEmailData, ThrowOnError>
): RequestResult<
  ChangeUserEmailResponses,
  ChangeUserEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChangeUserEmailResponses,
    ChangeUserEmailErrors,
    ThrowOnError
  >({
    url: '/api/user/management/email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const convertOidcUser = <ThrowOnError extends boolean = false>(
  options: Options<ConvertOidcUserData, ThrowOnError>
): RequestResult<
  ConvertOidcUserResponses,
  ConvertOidcUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ConvertOidcUserResponses,
    ConvertOidcUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management/convert-oidc',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const userInfoDetail = <ThrowOnError extends boolean = false>(
  options: Options<UserInfoDetailData, ThrowOnError>
): RequestResult<UserInfoDetailResponses, UserInfoDetailErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UserInfoDetailResponses,
    UserInfoDetailErrors,
    ThrowOnError
  >({ url: '/api/user/management/{uuid}', ...options });

export const listCachesSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesSimpleData, ThrowOnError>
): RequestResult<
  ListCachesSimpleResponses,
  ListCachesSimpleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCachesSimpleResponses,
    ListCachesSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/caches', ...options });

export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
): RequestResult<UpdatePasswordResponses, UpdatePasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdatePasswordResponses,
    UpdatePasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/account/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const startEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<StartEmailChangeData, ThrowOnError>
): RequestResult<
  StartEmailChangeResponses,
  StartEmailChangeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StartEmailChangeResponses,
    StartEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>
): RequestResult<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    url: '/api/user/account/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const confirmEmailChange = <ThrowOnError extends boolean = false>(
  options: Options<ConfirmEmailChangeData, ThrowOnError>
): RequestResult<
  ConfirmEmailChangeResponses,
  ConfirmEmailChangeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ConfirmEmailChangeResponses,
    ConfirmEmailChangeErrors,
    ThrowOnError
  >({
    url: '/api/user/account/email_change_confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAvatarData, ThrowOnError>
): RequestResult<UpdateAvatarResponses, UpdateAvatarErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UpdateAvatarResponses,
    UpdateAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/account/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const info = <ThrowOnError extends boolean = false>(
  options?: Options<InfoData, ThrowOnError>
): RequestResult<InfoResponses, InfoErrors, ThrowOnError> =>
  (options?.client ?? client).get<InfoResponses, InfoErrors, ThrowOnError>({
    url: '/api/user/info',
    ...options
  });

export const avatarById = <ThrowOnError extends boolean = false>(
  options: Options<AvatarByIdData, ThrowOnError>
): RequestResult<AvatarByIdResponses, AvatarByIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    AvatarByIdResponses,
    AvatarByIdErrors,
    ThrowOnError
  >({ url: '/api/user/info/avatar/{uuid}', ...options });

export const getGeneralSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeneralSettingsData, ThrowOnError>
): RequestResult<
  GetGeneralSettingsResponses,
  GetGeneralSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetGeneralSettingsResponses,
    GetGeneralSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/general', ...options });

export const getUserSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserSettingsData, ThrowOnError>
): RequestResult<
  GetUserSettingsResponses,
  GetUserSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUserSettingsResponses,
    GetUserSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/user', ...options });

export const saveUserSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveUserSettingsData, ThrowOnError>
): RequestResult<
  SaveUserSettingsResponses,
  SaveUserSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveUserSettingsResponses,
    SaveUserSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getMailSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetMailSettingsData, ThrowOnError>
): RequestResult<
  GetMailSettingsResponses,
  GetMailSettingsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetMailSettingsResponses,
    GetMailSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/mail', ...options });

export const saveMailSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveMailSettingsData, ThrowOnError>
): RequestResult<
  SaveMailSettingsResponses,
  SaveMailSettingsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveMailSettingsResponses,
    SaveMailSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/mail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const sendResetLink = <ThrowOnError extends boolean = false>(
  options: Options<SendResetLinkData, ThrowOnError>
): RequestResult<SendResetLinkResponses, SendResetLinkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SendResetLinkResponses,
    SendResetLinkErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
): RequestResult<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ResetPasswordResponses,
    ResetPasswordErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testMail = <ThrowOnError extends boolean = false>(
  options?: Options<TestMailData, ThrowOnError>
): RequestResult<TestMailResponses, TestMailErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TestMailResponses,
    TestMailErrors,
    ThrowOnError
  >({ url: '/api/mail/test', ...options });

export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
): RequestResult<DeleteGroupResponses, DeleteGroupErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
): RequestResult<ListGroupsResponses, ListGroupsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({ url: '/api/group', ...options });

export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
): RequestResult<CreateGroupResponses, CreateGroupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editGroup = <ThrowOnError extends boolean = false>(
  options: Options<EditGroupData, ThrowOnError>
): RequestResult<EditGroupResponses, EditGroupErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditGroupResponses,
    EditGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const groupInfo = <ThrowOnError extends boolean = false>(
  options: Options<GroupInfoData, ThrowOnError>
): RequestResult<GroupInfoResponses, GroupInfoErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GroupInfoResponses,
    GroupInfoErrors,
    ThrowOnError
  >({ url: '/api/group/{uuid}', ...options });

export const listUsersSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersSimpleData, ThrowOnError>
): RequestResult<
  ListUsersSimpleResponses,
  ListUsersSimpleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListUsersSimpleResponses,
    ListUsersSimpleErrors,
    ThrowOnError
  >({ url: '/api/group/users', ...options });

export const listCachesSimpleGroup = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesSimpleGroupData, ThrowOnError>
): RequestResult<
  ListCachesSimpleGroupResponses,
  ListCachesSimpleGroupErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCachesSimpleGroupResponses,
    ListCachesSimpleGroupErrors,
    ThrowOnError
  >({ url: '/api/group/caches', ...options });

export const newCode = <ThrowOnError extends boolean = false>(
  options?: Options<NewCodeData, ThrowOnError>
): RequestResult<NewCodeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<NewCodeResponses, unknown, ThrowOnError>({
    url: '/api/cli',
    ...options
  });

export const getToken = <ThrowOnError extends boolean = false>(
  options: Options<GetTokenData, ThrowOnError>
): RequestResult<GetTokenResponses, GetTokenErrors, ThrowOnError> =>
  (options.client ?? client).put<
    GetTokenResponses,
    GetTokenErrors,
    ThrowOnError
  >({ url: '/api/cli', ...options });

export const deleteCache = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCacheData, ThrowOnError>
): RequestResult<DeleteCacheResponses, DeleteCacheErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteCacheResponses,
    DeleteCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listCaches = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesData, ThrowOnError>
): RequestResult<ListCachesResponses, ListCachesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListCachesResponses,
    ListCachesErrors,
    ThrowOnError
  >({ url: '/api/cache/management', ...options });

export const createCache = <ThrowOnError extends boolean = false>(
  options: Options<CreateCacheData, ThrowOnError>
): RequestResult<CreateCacheResponses, CreateCacheErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateCacheResponses,
    CreateCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const clearCache = <ThrowOnError extends boolean = false>(
  options: Options<ClearCacheData, ThrowOnError>
): RequestResult<ClearCacheResponses, ClearCacheErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    ClearCacheResponses,
    ClearCacheErrors,
    ThrowOnError
  >({ url: '/api/cache/management/{uuid}', ...options });

export const cacheDetails = <ThrowOnError extends boolean = false>(
  options: Options<CacheDetailsData, ThrowOnError>
): RequestResult<CacheDetailsResponses, CacheDetailsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    CacheDetailsResponses,
    CacheDetailsErrors,
    ThrowOnError
  >({ url: '/api/cache/management/{uuid}', ...options });

export const editCache = <ThrowOnError extends boolean = false>(
  options: Options<EditCacheData, ThrowOnError>
): RequestResult<EditCacheResponses, EditCacheErrors, ThrowOnError> =>
  (options.client ?? client).post<
    EditCacheResponses,
    EditCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const searchStorePaths = <ThrowOnError extends boolean = false>(
  options: Options<SearchStorePathsData, ThrowOnError>
): RequestResult<
  SearchStorePathsResponses,
  SearchStorePathsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SearchStorePathsResponses,
    SearchStorePathsErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deletePath = <ThrowOnError extends boolean = false>(
  options: Options<DeletePathData, ThrowOnError>
): RequestResult<DeletePathResponses, DeletePathErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeletePathResponses,
    DeletePathErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}/path',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadInfo = <ThrowOnError extends boolean = false>(
  options: Options<UploadInfoData, ThrowOnError>
): RequestResult<UploadInfoResponses, UploadInfoErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadInfoResponses,
    UploadInfoErrors,
    ThrowOnError
  >({
    url: '/api/cache/push/info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadPath = <ThrowOnError extends boolean = false>(
  options: Options<UploadPathData, ThrowOnError>
): RequestResult<UploadPathResponses, UploadPathErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadPathResponses,
    UploadPathErrors,
    ThrowOnError
  >({
    url: '/api/cache/push',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadNar = <ThrowOnError extends boolean = false>(
  options: Options<UploadNarData, ThrowOnError>
): RequestResult<UploadNarResponses, UploadNarErrors, ThrowOnError> =>
  (options.client ?? client).post<
    UploadNarResponses,
    UploadNarErrors,
    ThrowOnError
  >({ url: '/api/cache/push/{uuid}', ...options });

export const uploadFinish = <ThrowOnError extends boolean = false>(
  options: Options<UploadFinishData, ThrowOnError>
): RequestResult<UploadFinishResponses, UploadFinishErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UploadFinishResponses,
    UploadFinishErrors,
    ThrowOnError
  >({
    url: '/api/cache/push/{uuid}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const test = <ThrowOnError extends boolean = false>(
  options?: Options<TestData, ThrowOnError>
): RequestResult<TestResponses, TestErrors, ThrowOnError> =>
  (options?.client ?? client).get<TestResponses, TestErrors, ThrowOnError>({
    url: '/api/cache/test',
    ...options
  });

export const deleteToken = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTokenData, ThrowOnError>
): RequestResult<DeleteTokenResponses, DeleteTokenErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteTokenResponses,
    DeleteTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listTokens = <ThrowOnError extends boolean = false>(
  options?: Options<ListTokensData, ThrowOnError>
): RequestResult<ListTokensResponses, ListTokensErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListTokensResponses,
    ListTokensErrors,
    ThrowOnError
  >({ url: '/api/token', ...options });

export const createToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateTokenData, ThrowOnError>
): RequestResult<CreateTokenResponses, CreateTokenErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateTokenResponses,
    CreateTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editToken = <ThrowOnError extends boolean = false>(
  options: Options<EditTokenData, ThrowOnError>
): RequestResult<EditTokenResponses, EditTokenErrors, ThrowOnError> =>
  (options.client ?? client).put<
    EditTokenResponses,
    EditTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deleteExpiredTokens = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteExpiredTokensData, ThrowOnError>
): RequestResult<
  DeleteExpiredTokensResponses,
  DeleteExpiredTokensErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteExpiredTokensResponses,
    DeleteExpiredTokensErrors,
    ThrowOnError
  >({ url: '/api/token/expired', ...options });

export const tokenInfo = <ThrowOnError extends boolean = false>(
  options: Options<TokenInfoData, ThrowOnError>
): RequestResult<TokenInfoResponses, TokenInfoErrors, ThrowOnError> =>
  (options.client ?? client).get<
    TokenInfoResponses,
    TokenInfoErrors,
    ThrowOnError
  >({ url: '/api/token/{uuid}', ...options });

export const tokenRegenerate = <ThrowOnError extends boolean = false>(
  options: Options<TokenRegenerateData, ThrowOnError>
): RequestResult<
  TokenRegenerateResponses,
  TokenRegenerateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TokenRegenerateResponses,
    TokenRegenerateErrors,
    ThrowOnError
  >({ url: '/api/token/{uuid}', ...options });
