// This file is auto-generated by @hey-api/openapi-ts

import type {
  CacheDetailsResponse,
  ListCachesResponse,
  ListTokensResponse,
  SearchStorePathsResponse,
  TokenInfoResponse
} from './types.gen';

const cacheInfoSchemaResponseTransformer = (data: any) => {
  data.quota = BigInt(data.quota.toString());
  if (data.size) {
    data.size = BigInt(data.size.toString());
  }
  return data;
};

export const listCachesResponseTransformer = async (
  data: any
): Promise<ListCachesResponse> => {
  data = data.map((item: any) => cacheInfoSchemaResponseTransformer(item));
  return data;
};

const cacheDetailsSchemaResponseTransformer = (data: any) => {
  data.nar_count = BigInt(data.nar_count.toString());
  data.quota = BigInt(data.quota.toString());
  if (data.size) {
    data.size = BigInt(data.size.toString());
  }
  return data;
};

export const cacheDetailsResponseTransformer = async (
  data: any
): Promise<CacheDetailsResponse> => {
  data = cacheDetailsSchemaResponseTransformer(data);
  return data;
};

const searchResultSchemaResponseTransformer = (data: any) => {
  data.accessed = BigInt(data.accessed.toString());
  data.created_at = new Date(data.created_at);
  if (data.last_accessed_at) {
    data.last_accessed_at = new Date(data.last_accessed_at);
  }
  data.size = BigInt(data.size.toString());
  return data;
};

export const searchStorePathsResponseTransformer = async (
  data: any
): Promise<SearchStorePathsResponse> => {
  data = data.map((item: any) => searchResultSchemaResponseTransformer(item));
  return data;
};

const tokenInfoSchemaResponseTransformer = (data: any) => {
  data.exp = new Date(data.exp);
  if (data.last_used) {
    data.last_used = new Date(data.last_used);
  }
  return data;
};

export const listTokensResponseTransformer = async (
  data: any
): Promise<ListTokensResponse> => {
  data = data.map((item: any) => tokenInfoSchemaResponseTransformer(item));
  return data;
};

export const tokenInfoResponseTransformer = async (
  data: any
): Promise<TokenInfoResponse> => {
  data = tokenInfoSchemaResponseTransformer(data);
  return data;
};
