name: Flake Build

on:
  pull_request:
  release:
    types:
      - published

jobs:
  flake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Install Hibernation CLI
        uses: profiidev/hibernation@v0
        with:
          url: ${{ secrets.HIBERNATION_URL }}
          token: ${{ secrets.HIBERNATION_TOKEN }}
          signing-key: ${{ secrets.HIBERNATION_SIGNING_KEY }}

      - name: Run build
        run: nix build . -Lv --print-out-paths --accept-flake-config

      - name: Cache results
        if: github.event_name != 'pull_request'
        run: |
          RESULT_PATH=$(readlink result)
          hibernation push projects $RESULT_PATH
