name: Lock Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight UTC

jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31

      - name: Update components
        run: |
          nix flake update

      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore: updated flake lock"
          branch: "chore/update-flake-lock-${{ github.run_id }}"
          title: "chore: update flake lock"
          body: "This PR updates the flake inputs to the latest versions."
          base: main
          sign-commits: true
          labels: flake-lock-update
